# Generated by Django 4.1.7 on 2023-03-11 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_details',
            name='mobile',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
