# Generated by Django 4.1.7 on 2023-04-05 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_user_details_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='solutions',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
