# Generated by Django 4.1.7 on 2023-04-05 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_solutions_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solutions',
            name='upvote',
        ),
    ]
