# Generated by Django 4.1.7 on 2023-04-08 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_details',
            name='profile_image',
            field=models.ImageField(default='blank_profile.png', null=True, upload_to='profile'),
        ),
    ]
