# Generated by Django 4.1.3 on 2023-04-29 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_user_details_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_details',
            name='reputation',
            field=models.IntegerField(default=0),
        ),
    ]
